### ISSUE TITLE
question about contribution

### ISSUE THREAD

**Issue by menachem-dev** [argosopentech/onmt-models#1]
Hey, I'm not at all a programmer nor do I really understand the tech speech but I heard about this project and I was wondering it was a way for me to help? I am fluent in English and Hebrew (which I saw you didn't have) (I don't even understand if knowing the language is important)?

**Comment by PJ-Finlay** [comment]
Check out the "Good First Issues" on the main repo. Also: https://github.com/argosopentech/argos-translate/issues/15
