### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by seekingdeep** [argosopentech/onmt-models#2]
@PJ-Finlay Hi there,
Currently i have interest in machine translation, with an eye on the Arabic, Urdu and English languages.
My target for now is to learn how to train a new model from scratch. therefor the following questions arise:
- How does onmt compares with the other machine translation models such as mt5, [criss](https://github.com/pytorch/fairseq/tree/master/examples/criss) , XLM-RoBERTa
- How many parameters does onmt model have, and what is it's performance to translate 100 sentences on a cpu only device (ram usage, cpu usage, time required, etc...)
Waiting for your reply

**Comment by PJ-Finlay** [comment]
From scratch not using Argos Translate? I would look at the training scripts to see how the tokenizer and sentence boundary detection work. These may be better questions for the OpenNMT forum.
