### ISSUE TITLE
prepare_data.py is appending multiple (nine) copies of source and target lines to train and val files

### ISSUE THREAD

**Issue by ahirsbrunner** [argosopentech/onmt-models#7]
The issue is lines 38 and 39  in prepare_data.py are being called once for every naughty_string type, so source.append and target.append are being called nine times for every valid source/target line (once for each type of naughty_string).

lines 38 and 39 should not be in the loop on line 35, and should be move left one level.

38         source.append(source_line)
39         target.append(target_line)

Best Regards

![prepare_data py](https://user-images.githubusercontent.com/89089422/129752530-d267ff5b-f028-408f-bb5a-a62f13c9a583.png)

**Comment by PJ-Finlay** [comment]
Great catch thanks!

Potentially the partial cause of [this](https://github.com/google/sentencepiece/issues/682) bug by overloading SentencePiece but I won't be able to fully test for another week.
